name: reviewdog
on: [pull_request]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: true

  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-misspell@v1
        with:
          reporter: github-pr-review
          level: warning
          filter_mode: diff_context
          fail_on_error: true
